default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 10000
  port: 5432

development:
  <<: *default
  host: localhost
  database: pecaiet_dev

test:
  <<: *default
  database: pecaiet_test

production:
  <<: *default
  username: nkbowdfaeotukr
  password: cdc39479771113e9bf49143c7fb77ee63ae900f09a699aeab94f44d02c6160ba
  host: ec2-54-73-22-169.eu-west-1.compute.amazonaws.com
  database: dfb0iom4p10hac